name: pass_datafromjob1
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.set_output.outputs.message }}
    steps:
      - name: set output message
        run: |
          echo "message = hello from job 1" >> $GITHUB_OUTPUT
          echo "set output: hi"
          echo "set second output: welcome to githubactions"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: print recieved output
        run: |
         echo "message from job1:${{needs.job1.outputs.message}}"
  
          
          
        
  
