name: passing_file
on: 
  push:
    branches: [main]
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
       - name: create data
         run: echo "myfile Ansible is an open-source automation tool used for

Configuration management – ensuring servers are set up in a consistent way

Application deployment – installing or updating software on multiple machines

Task automation – automating repetitive tasks like backups or updates

Orchestration – coordinating complex processes across multiple systems

It is agentless, which means you don’t need to install any software on the servers you manage. Ansible uses SSH (for Linux) or WinRM (for Windows) to communicate." >> file.txt
       - name: upload file
         uses: actions/upload-artifact@v4
         with:
           name: file_data
           path: file.txt
  job2:
   needs: job1
   runs-on: ubuntu-latest
   steps:
     - name: download_artifact
       uses: actions/download-artifact@v4
       with:
           name: file_data
     - name: read data
       run: cat file.txt
       run: find s file.txt
       run: head file.txt
       
     
