name: secrets & vars
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Repository variables demo
       run: |
        echo "APP_NAME: ${{vars.APP_NAME}}"
        echo "DEPLOY_REGION: ${{vars.DEPLOY_REGION}}"
     - name: secrets demo(masked)
       env:
         DEMO_SECRET: ${{secrets.DEMO_SECRET}}
       run: |
           echo "secret length is: ${#DEMO_SECRET}"
        
   
