name: pass_datafromjob1
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set output message
        run: |
          echo "second message =$second message" >> $GITHUB_OUTPUT
          echo "set output: hi"
          echo "set second output: welcome to githubactions"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: print recieved output
        run: |
         echo "message from job1:${{needs.job1.outputs.message}}"
  
          
          
        
  
