name: secrets & vars
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Repository variables demo
       run: |
        echo "APP_NAME: ${{vars.APP_NAME}}"
        echo "ENV_VAR: ${{vars.ENV_VAR}}"
     - name: secrets demo(masked)
       env:
         SECRET_NAME: ${{secrets.SECRET_NAME}}
       run: |
           echo "secret length is: ${#SECRET_NAME}"
        
   
