name: demo8
on: 
  workflow_dispatch:
    inputs:
      job-to-run:
      description: "which job to run(job1, job2, job3)"
      required: true
      type: choice
      options:
        -job1
        -job2
        -job3
  #push: 
    #branches: [main, develop, test]
    #branches:
      #- main
      #- develop
      #- test
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: this first job
        run: echo "first job"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: this second job
        run: echo "second job"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: this third job
        run: echo "third job"
